---
networks:
  yarr_net: {}

volumes:
  yarr_data: {}

services:

  yarr:
    image: itsnoted/yarr
    container_name: yarr
    restart: unless-stopped
    ports:
      - ${YARR_PORT:-7070}:7070
    volumes:
      - ${YARR_DATA_DIR:-yarr_data}:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - yarr_net

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_yarr
    restart: unless-stopped
    pull_policy: always
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: "true"
      ## Only update containers with the
      #  "com.centurylinklabs.watchtower.enable=true" label
      WATCHTOWER_LABEL_ENABLE: "true"
      ## Check for updates every 300 seconds (5 minutes)
      WATCHTOWER_POLL_INTERVAL: 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - yarr_net
