---
networks:
  yarr_net: {}

volumes:
  yarr_data: {}

services:
  yarr:
    image: itsnoted/yarr
    container_name: yarr
    restart: unless-stopped
    ports:
      - ${YARR_PORT:-7070}:7070
    volumes:
      - ${YARR_DATA_DIR:-yarr_data}:/data
    networks:
      - yarr_net
