---
# networks:
#   unnamed_net: {}

# volumes:
#   volume_name: {}

services:
  zot:
    image: "ghcr.io/project-zot/zot-linux-amd64:latest"
    container_name: zot-registry
    restart: unless-stopped
    ports:
      - ${ZOT_REGISTRY_PORT:-5000}:5000
