version: "3"

networks:
  gitea:
    external: false

services:
  
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ${GITEA_DATA_DIR:-./data}:/data
      - ${GITEA_SSH_DIR:-./ssh}:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_HTTP_PORT:-3000}:3000
      - ${GITEA_SSH_PORT:-2222}:22

