version: '3'

networks:
  web-proxy:
    external:
      name: web-proxy

services:
  # Emby media server
  emby:
      container_name: ${EMBY_NAME:-emby}
      image: ${EMBY_IMAGE:-emby/embyserver:latest}
      restart: ${EMBY_RESTART:-unless-stopped}
      ports:
      - ${EMBY_HTTP_PORT:-8096}:8096
      - ${EMBY_HTTPS_PORT:-8920}:8920
      volumes:
      - ${EMBY_CONFIG_DIR:-./config}:/config
      - ${EMBY_MEDIA_DIR:-./media}:/mnt/multimedia
      environment:
      - VIRTUAL_PORT=${EMBY_VIRTUAL_PORT:-8096}
      - VIRTUAL_HOST=${EMBY_VIRTUAL_HOST:-emby.htpc}
      - AUTO_UPDATES_ON=${EMBY_AUTO_UPDATES:-true}
      - APP_UID=${EMBY_APP_UID:-1000}
      - APP_GID=${EMBY_APP_GID:-1000}
      networks:
      - web-proxy
