name: authentik

services:
  postgresql:
    image: postgres:${POSTGRES_IMG_TAG:-16-alpine}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    volumes:
      - ${POSTGRES_DATA_DIR:-./database}:/var/lib/postgresql/data

  server:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMG_TAG:-2026.8.1}
    command: server
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: ${TZ:-Etc/UTC}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:?database password required}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ENABLE_TELEMETRY:-false}

      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_SMTP_HOST:-}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_SMTP_PORT:-587}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_SMTP_USERNAME:-}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_SMTP_PASSWORD:-}
      AUTHENTIK_EMAIL__USE_TLS: ${AUTHENTIK_SMTP_USE_TLS:-true}
      AUTHENTIK_EMAIL__USE_SSL: ${AUTHENTIK_SMTP_USE_SSL:-false}
      AUTHENTIK_EMAIL__TIMEOUT: ${AUTHENTIK_SMTP_TIMEOUT:-10}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_SMTP_FROM_ADDR:-}
    ports:
      - ${AUTHENTIK_HTTP_PORT:-9000}:9000
      - ${AUTHENTIK_HTTPS_PORT:-9443}:9443
    shm_size: 512mb
    volumes:
      - ${AUTHENTIK_DATA_DIR:-./data}:/data
      - ${AUTHENTIK_TEMPLATES_DIR:-./custom-templates}:/templates

  worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_IMG_TAG:-2026.8.1}
    command: worker
    restart: unless-stopped
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      TZ: ${TZ:-Etc/UTC}
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS:?database password required}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      AUTHENTIK_ERROR_REPORTING__ENABLED: ${AUTHENTIK_ENABLE_TELEMETRY:-false}
    shm_size: 512mb
    ## Uncomment if using Docker Outposts
    #  https://docs.goauthentik.io/add-secure-apps/outposts/
    # user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${AUTHENTIK_DATA_DIR:-./data}:/data
      - ${AUTHENTIK_CERTS_DIR:-./certs}:/certs
      - ${AUTHENTIK_TEMPLATES_DIR:-./custom-templates}:/templates
