---
name: n8n

volumes:
  ntfy_data: {}

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    user: ${NTFY_UID:-1000}:${NTFY_GID:-1000}
    ports:
      - ${NTFY_PORT:-80}:80
    environment:
      TZ: ${TZ:-UTC}
      NTFY_BASE_URL: ${NTFY_BASE_URL:-http://127.0.0.1:80}
      NTFY_AUTH_DEFAULT_ACCESS: ${NTFY_AUTH_ACCESS_POLICY:-deny-all}
      NTFY_BEHIND_PROXY: ${NTFY_PROXIED:-false}
      NTFY_ENABLE_SIGNUP: ${NTFY_SIGNUP_ENABLED:-false}
      ## Enable file attachments by uncommenting section below
      NTFY_ATTACHMENT_CACHE_DIR: "/var/lib/ntfy/attachments"
      NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT: ${NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT:-5G}
      NTFY_ATTACHMENT_FILE_SIZE_LIMIT: ${NTFY_ATTACHMENT_FILE_SIZE_LIMIT:-15M}
      NTFY_ATTACHMENT_EXPIRY_DURATION: ${NTFY_ATTACHMENT_EXPIRY_DURATION:-3h}
    volumes:
      - ${NTFY_CACHE_DIR:-./ntfy/cache}:/var/cache/ntfy
      - ${NTFY_CONFIG_DIR:-./ntfy/config}:/etc/ntfy
      - ${NTFY_DB_DIR:-./ntfy/db}:/var/lib/ntfy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
