version: '3'

networks:
  seafile-net:
    driver: bridge
  web-proxy:
      external:
          name: web-proxy

services:

  seafile-db:
    image: ${SEAFILE_DB_IMAGE:-mariadb:10.1}
    container_name: ${SEAFILE_DB_NAME:-seafile-db}
    restart: ${SEAFILE_DB_RESTART:-unless-stopped}
    environment:
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD:-seafile}
      - MYSQL_LOG_CONSOLE=${SEAFILE_DB_LOG_CONSOLE:-true}
    volumes:
      - ${SEAFILE_DB_DIR:-./seafile-mysql/db}:/var/lib/mysql
    networks:
      - seafile-net
    
  memcached:
    image: ${SEAFILE_MEMCACHED_IMAGE:-memcached:1.5.6}
    container_name: ${SEAFILE_MEMCACHED_NAME:-seafile-memcached}
    restart: ${SEAFILE_MEMCACHED_RESTART:-unless-stopped}
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: ${SEAFILE_IMAGE:-seafileltd/seafile-mc:latest}
    container_name: ${SEAFILE_NAME:-seafile}
    restart: ${SEAFILE_RESTART:-unless-stopped}
    networks:
      - seafile-net
      - web-proxy
      - default
    links:
      - seafile-db:db
    depends_on:
      - memcached
      - seafile-db
    ports:
      - ${SEAFILE_HTTP_PORT:-8080}:80
      - ${SEAFILE_HTTPS_PORT:-8443}:443
    # expose:
    #  - "80"
    volumes:
      - ${SEAFILE_DATA_DIR:-./data}:/shared
    environment:
      - DB_HOST=${SEAFILE_DB_NAME:-seafile-db}
      - DB_ROOT_PASSWD=${SEAFILE_ROOT_PASSWORD}
      # - TIME_ZONE=${TZ}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL:-seafile@example.com}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD:-seafile}