---
name: enshrouded

volumes:
  server_data: {}

services:
  enshrouded:
    image: mornedhels/enshrouded-server:${ENSHROUDED_SERVER_IMG_TAG:-latest}
    container_name: enshrouded
    hostname: enshrouded
    restart: unless-stopped
    stop_grace_period: 90s
    ports:
      - "${ENSHROUDED_SERVER_PORT:-15637}:15637/udp"
    volumes:
      - ${SERVER_DATA_DIR:-server_data}:/opt/enshrouded
    env_file:
      - ./env_files/game_options.env
    environment:
      TZ: ${TZ:-Etc/UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      SERVER_NAME: ${SERVER_NAME:-Embervale Friends}
      SERVER_SLOT_COUNT: ${SERVER_SLOT_COUNT:-16}
      SERVER_QUERYPORT: 15637
      SERVER_IP: ${SERVER_IP:-0.0.0.0}
      SERVER_SAVE_DIR: ./savegame
      SERVER_LOG_DIR: ./logs
      BACKUP_DIR: ./backup
      BACKUP_CRON: ${SERVER_BACKUP_CRON:-*/4 * * *}
      BACKUP_MAX_COUNT: ${SERVER_BACKUP_MAX_COUNT:-0}
      SERVER_VOICE_CHAT_MODE: ${SERVER_VOICE_CHAT_MODE:-Proximity}
      SERVER_ENABLE_VOICE_CHAT: ${SERVER_ENABLE_VOICE_CHAT:-false}
      SERVER_ENABLE_TEXT_CHAT: ${SERVER_ENABLE_TEXT_CHAT:-true}
      UPDATE_CRON: ${SERVER_UPDATE_CHECK_CRON:-*/30 * * * *}
      UPDATE_CHECK_PLAYERS: ${SERVER_SKIP_UPDATE_WHEN_PLAYERS_CONNECTED:-true}

      ## Admin group
      SERVER_ROLE_0_NAME: Admins
      SERVER_ROLE_0_PASSWORD: ${SERVER_ADMIN_PASSWORD:-enshroudedAdmin}
      SERVER_ROLE_0_CAN_KICK_BAN: true
      SERVER_ROLE_0_CAN_ACCESS_INVENTORIES: true
      SERVER_ROLE_0_CAN_EDIT_BASE: true
      SERVER_ROLE_0_CAN_EXTEND_BASE: true
      SERVER_ROLE_0_RESERVED_SLOTS: 1

      SERVER_ROLE_1_NAME: Friends
      SERVER_ROLE_1_PASSWORD: ${SERVER_FRIENDS_PASSWORD:-enshroudedFriends}
      SERVER_ROLE_1_CAN_ACCESS_INVENTORIES: true
      SERVER_ROLE_1_CAN_EDIT_BASE: true
      SERVER_ROLE_1_CAN_EXTEND_BASE: true
      SERVER_ROLE_1_RESERVED_SLOTS: 3

      SERVER_ROLE_2_NAME: Guests
      SERVER_ROLE_2_PASSWORD: ${SERVER_GUEST_PASSWORD:-enshroudedGuest}
      SERVER_ROLE_2_RESERVED_SLOTS: 0

      GAME_BRANCH: ${SERVER_GAME_BRANCH:-public}
      STEAMCMD_ARGS: ${SERVER_STEAMCMD_ARGS:-validate}

      log_level: ${SERVER_LOG_LEVEL:-40}
