version: "3"

networks:
  default:
    external:
      # This network needs to be declared at the top of
      # each Wordpress instance's docker-compose.yml
      name: proxy_net

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/html:/usr/share/nginx/html
      - ${PROXY_CERT_PATH:-./conf/certs}:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  cloudflare-companion:
    image: tiredofit/nginx-proxy-cloudflare-companion
    restart: unless-stopped
    container_name: nginx-proxy_cloudflare
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CF_EMAIL: ${PROXY_CF_EMAIL}
      CF_TOKEN: ${PROXY_CF_TOKEN}
      TARGET_DOMAIN: ${WILDCARD_DOMAIN}
      DOMAIN1: ${DOMAIN}
      DOMAIN1_ZONE_ID: ${PROXY_CF_DOMAIN1_ZONE_ID}
      DOMAIN1_PROXIED: ${PROXY_DOMAIN1_PROXIED:-1}
      DOCKER_CERT_PATH: ${PROXY_CERT_PATH:-./conf/certs}
      DOCKER_TLS_VERIFY: ${PROXY_TLS_VERIFY:-1}
      TARGET_DOMAIN: ${WILDCARD_DOMAIN}

  whoami:
    image: jwilder/whoami
    container_name: nginx-proxy_whoami
    environment:
      VIRTUAL_HOST: whoami.local