---
networks:
  jupyterhub_net: {}

volumes:
  jupyterhub-data: {}

services:

  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - HOST
    ports:
      - ${JUPYTER_HUB_PORT:-8000}:8000
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.frontend.rule=Host:${HOST}"
    

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  reverse-proxy:
    image: traefik
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      - /etc/certs:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
