version: "3"

# networks:
#   frontend:
#   backend:

volumes:
  node_server-modules:

services:

  node_server:
    container_name: node_server
    restart: unless-stopped
    build:
      context: ./
      target: ${NODE_TARGET:-production}
    # command: npm start
    command: npm run start:${NODE_ENV:-production}
    volumes:
      - ${NODE_APP_DIR:-./src}:/src
      # Specify a node_modules dir to persist installed modules between containers
      - ${NODE_MODULES_DIR:-node_server-modules}:/src/node_modules
      # - ${NODE_LOGS_DIR:-./logs}:/root/.npm/_logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NODE_PORT=${NODE_PORT:-8080}
      - LOG_LEVEL=${NODE_LOG_LEVEL:-info}
      - DEBUG=nodejs-docker-express:*
    ports:
      - ${NODE_PORT:-8080}:8080
    # depends_on:
    #   - node_server-db
    # environment:
    #   DATABASE_URL: node_server-db://todoapp@postgres/todos
    # networks:
    #   - frontend
    #   - backend

  # node_server-db:
  #   container_name: node_server-db
  #   restart: unless-stopped
  #   image: postgres:14-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos
  #   networks:
  #     - backend