version: '3'

services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: "${LINKDING_CONTAINER_NAME:-linkding}"
    restart: unless-stopped
    environment:
      LD_SUPERUSER_NAME: ${LINKDING_SUPERUSER:-admin}
      LD_SUPERUSER_PASSWORD: ${LINKDING_SUPERUSER_PASSWORD:-linkding}
    ports:
      - "${LINKDING_HTTP_PORT:-9090}:9090"
    volumes:
      - "${LINKDING_DATA_DIR:-./linkding/data}:/etc/linkding/data"
