---
services:
  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    ports:
      - "${HEADSCALE_HTTP_PORT:-8080}:8080"
      - "${HEADSCALE_HTTPS_PORT:-9090}:9090"
    volumes:
      - ${HEADSCALE_CONFIG_DIR:-./headscale/config}:/etc/headscale
    command: serve
