---
name: calibre

services:
  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: ${CALIBRE_NAME:-calibre}
    restart: unless-stopped
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-America/New_York}
    volumes:
      - ${CALIBRE_CONFIG_DIR:-./calibre/config}:/config
      - ${CALIBRE_UPLOADS_DIR:-./calibre/uploads}:/uploads
      - ${CALIBRE_PLUGINS_DIR:-./calibre/plugins}:/plugins
      - ${CALIBRE_BOOKS_DIR:-./calibre/CalibreLibrary}:/books
    ports:
      - ${CALIBRE_HTTP_PORT:-8080}:8080
      - ${CALIBRE_HTTPS_PORT:-8081}:8081
      - ${CALIBRE_APP_PORT:-8181}:8181
