#################################################
# Public upload/drop-box                        #
#                                               #
# Anyone can upload files.                      #
# Anonymous users cannot browse the directory.  #
# The administrator can manage everything.      #
#                                               #
# Useful for receiving files from other people. #
#################################################

[global]

e2dsa


[accounts]

admin: change-this-password


[/]

/w

accs:
  ## Anyone can upload.
  #  "w" = write/upload
  w: *

  ## Administrator can read, write, move, delete and administer.
  rwmda: admin

flags:
  ## Enable the uploads database.
  e2d
  
  ## Reject duplicate uploads.
  nodupe

[/upload]

/w/upload

accs:
  w: *
  rwmda: admin

flags:
  e2d
  nodupe
