##################################################################
# Public files, individual user directories, public upload area. #
##################################################################

[global]

e2dsa
e2ts


[accounts]

alice: change-this-password
bob: change-this-password
admin: change-this-password


[groups]

admins: admin


[/]

## Public files.
/w/public

accs:
  r: *

flags:
  e2ds


[/u/${u}]

## Each user's private directory.
/w/users/${u}

accs:
  ## The user can fully manage their own directory.
  rwmda: ${u}

  ## Administrators can manage all user directories.
  rwmda: @admins

flags:
  e2ds


[/upload]

## Public drop box.
/w/upload

accs:
  w: *

rwmda: @admins

flags:
  e2d
  nodupe
