---
services:
  beszel:
    image: 'henrygd/beszel'
    container_name: 'beszel'
    restart: unless-stopped
    ports:
      - ${BESZEL_WEBUI_PORT:-8090}:8090
    volumes:
      - ${BESZEL_DATA_DIR:-./beszel/data}:/beszel_data

