---
services:
  playwright-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest
    container_name: playwright-chrome
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    tmpfs:
      - /tmp

  changedetection:
    environment:
      PLAYWRIGHT_DRIVER_URL: ws://playwright-chrome:3000
