---
services:

  ###########################
  # Vanilla survival server #
  #   Type: VANILLA         #
  #   Mode: survival        #
  ###########################

  mc-server:
    image: itzg/minecraft-server
    container_name: ${MC_SERV_CONTAINER_NAME:-mc-server_example}
    restart: unless-stopped
    ## Comment if using mc-router container
    ports:
      - ${MC_SERV_PORT:-25565}:25565
    tty: ${MC_SERV_TTY:-true}
    stdin_open: true
    environment:
      VERSION: ${MC_SERV_VERSION:-LATEST}
      TYPE: ${MC_SERV_TYPE:-VANILLA}
      MODE: ${MC_SERV_GAME_MODE:-survival}
      MOTD: ${MC_SERV_MOTD:-Welcome to the server!}
      EULA: "TRUE"
      DIFFICULTY: ${MC_SERV_DIFFICULTY:-normal}
      # https://github.com/itzg/docker-minecraft-server#memory-limit
      MEMORY: ${MC_SERV_MEMORY:-4G}
      ## Uncomment this to import a saved game from the defined WORLDS dir
      # WORLD: /worlds/${MC_SERV_WORLD}
      MAX_PLAYERS: ${MC_SERV_MAX_PLAYERS:-20}
      MAX_WORLD_SIZE: ${MC_SERV_MAX_WORLD_SIZE:-10000}
      ALLOW_NETHER: ${MC_SERV_ALLOW_NETHER:-true}
      ENABLE_COMMAND_BLOCK: ${MC_SERV_COMMAND_BLOCK:-true}
      MAX_BUILD_HEIGHT: ${MC_SERV_MAX_BUILD_HEIGHT:-256}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#max-tick-time
      MAX_TICK_TIME: ${MC_SERV_MAX_TICK_TIME:-60000}
      SNOOPER: false
      VIEW_DISTANCE: ${MC_SERV_VIEW_DISTANCE:-10}
      # LEVEL_SEED: ${MC_SERV_SEED:-""}
      PVP: ${MC_SERV_PVP:-true}
      ## https://github.com/itzg/docker-minecraft-server/blob/master/README.md#online-mode
      ONLINE_MODE: ${MC_SERV_ONLINE_MODE:-true}
      WHITELIST_FILE: /extra/whitelist.json
      WHITELIST_ENABLED: ${MC_SERV_WHITELIST_ENABLE:-false}
      OVERRIDE_WHITELIST: true
    volumes:
      - ${MC_SERV_DATA_DIR:-./data/minecraft-server}:/data
      # - ${MC_SERV_WORLD_IMPORT_DIR:-./worlds}:/worlds:ro
      - ${MC_SERV_WHITELIST_FILE:-./whitelist.json}:/extra/whitelist.json
    healthcheck:
      test: mc-health
      start_period: 1m
      interval: 5s
      retries: 20
