---
name: unifios

services:
  server:
    container_name: unifi-os-server
    image: ghcr.io/unihosted/unifi-os-server-docker:${UNIFIOS_IMG_TAG:-5.1.40}
    cgroup: host
    restart: unless-stopped
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - "${UNIFIOS_HTTP_PORT:-8080}:8080"
      - "${UNIFIOS_API_PORT:-8443}:8443"
      - "${UNIFIOS_HOTSPORT_PORTAL_PORT:-8444}:8444"
      - "${UNIFIOS_HOTSPOT_PORTAL_REDIRECT_PORT:-8880-8882}:8880-8882"
      - "${UNIFIOS_DISCOVERY_PORT:-10003}:10003/udp"
      - "${UNIFIOS_WEBUI_PORT:-11443}:443"
      - "${UNIFIOS_STUN_PORT:-3478}:3478/udp"
      - "${UNIFIOS_SYSLOG_PORT:-5514}:5514/udp"
      - "${UNIFIOS_SPEEDTEST_PORT:-6789}:6789"
      - "${UNIFIOS_DB_PORT:-127.0.0.1:5432}:5432"
      - "${UNIFIOS_MONGODB_PORT:-27117}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "host.containers.internal:host-gateway"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ${UNIFIOS_APP_DIR:-./uos}:/var/lib/uosserver
      - ${UNIFIOS_APP_DIR:-./uos}:/var/lib/unifi
      - ${UNIFIOS_DATA_DIR:-./data}:/data
    tmpfs:
      - /run:exec
      - /run/lock
      - /tmp:exec
      - /var/lib/journal
      - /var/opt/unifi/tmp:size=64m
      - /data/unifi-core/config/http
    environment:
      TZ: ${TZ:-Etc/UTC}
      UOS_SYSTEM_IP: "${UNIFIOS_SYSTEM_IP:-127.0.0.1}"
      MONGO_INTERNAL: ${UNIFIOS_USER_INTERNAL_MONGODB:-true}
