---
# networks:
#   unnamed_net: {}

volumes:
  mongo_data: {}
  unifi_config: {}

services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - MONGO_USER=${MONGO_USER:-unifi}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DB_NAME:-unifi}
      - MONGO_AUTHSOURCE=${MONGO_AUTHSOURCE:-admin}
      ## optional
      - MEM_LIMIT=${UNIFI_MEM_LIMIT:-1024}
      ## optional
      - MEM_STARTUP=${UNIFI_MEM_STARTUP:-1024}
      ## optional
      - MONGO_TLS=${MONGO_TLS}
    volumes:
      - ${UNIFI_CONFIG_DIR:-unifi_config}:/config
    ports:
      - ${UNIFI_WEBUI_PORT:-8443}:8443
      ## STUN
      - ${UNIFI_STUN_PORT:-3478}:3478/udp
      ## AP discovery
      - ${UNIFI_AP_DISCOVERY_PORT:-10001}:10001/udp
      ## Inform port (set-inform)
      - ${UNIFI_SET_INFORM_PORT:-8080}:8080
      ## optional
      #  make controller discoverable on L2 network
      - ${UNIFI_L2_DISCOVERY_PORT:-1900}:1900/udp
      ## optional
      #  guest portal HTTPS redirect
      - ${UNIFI_GUEST_PORTAL_REDIRECT_PORT:-8843}:8843
      ## optional
      #  guest portal HTTP redirect
      - ${UNIFI_GUEST_PORTAL_HTTP_REDIRECT_PORT:-8880}:8880
      ## optional
      #  mobile throughput test
      - ${UNIFI_MOBILE_THROUGHPUT_TEST_PORT:-6789}:6789
      ## optional
      #  remote syslog
      - ${UNIFI_REMOTE_SYSLOG_PORT:-5514}:5514/udp

  unifi-db:
    image: docker.io/mongo:${MONGO_CONTAINER_IMG_VER:-8.0.8}
    container_name: unifi-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER:-unifi}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DBNAME=${MONGO_DB_NAME:-unifi}
      - MONGO_AUTHSOURCE=${MONGO_AUTHSOURCE:-admin}
    volumes:
      - ${MONGO_DATA_DIR:-mongo_data}:/data/db
      - ${MONGO_INITDB_SCRIPT:-./mongo/init-mongo.sh}:/docker-entrypoint-initdb.d/init-mongo.sh:ro
