# yaml-language-server: $schema=https://raw.githubusercontent.com/cooperspencer/gickup/refs/heads/main/gickup_spec.json
log:
  timeformat: 2006-01-02 15:04:05
  file-logging:
    dir: log
    file: gickup.log
    maxage: 7

source:
  ## Use github repository as a source
  github:
    ## Set clone URL base, including git username
    - user: "your-username"
      ssh: true
      ## Path in container
      sshkey: "/root/.ssh/id_rsa"
      token_file: "/root/.ssh/github_token"
      ## Names of repositories to include
      include:

        ## This is where you put the names of the repos you want to synch.
        #  You can copy/paste from another config if you have one.
        - "repo1-name"
        - "repo2-name"

      ## wiki, starred, and issues require a PAT.
      wiki: true
      starred: false
      issues: true
      gists: true
      filter:
        # lastactivity: 1y
        excludearchived: false
        excludeforks: true
        # languages:
        #   - python
        #   - powershell
        #   - bash

destination:
  ## Backup to a local directory
  local:
    ## Path in container
    - path: "/backup/"

  ## Backup to a Codeberg repository
  gitea:
    - url: https://codeberg.org/
      user: your-username
      token_file: /root/.ssh/codeberg_token
      createorg: true
      lfs: true
      mirror:
        mirrorinterval: 8h
        enabled: true
      visibility:
        repositories: private
        organizations: private
      force: true

  ## Backup to an S3 bucket
  # s3:
  #   - endpoint: 192.168.1.18:9000
  #     structured: true
  #     bucket: gickup-backups
  #     accesskey: kyXN6QQSBfmHls4Z44Wz
  #     secretkey: dSbTPAy3W4zst0ivh7bQfv3fPmuDBF2YS5muTrKd
  #     usessl: false

  ## Backup to a Gitlab repository
  # gitlab:
  #   - token: some-token
  #     token_file: token.txt
  #     url: http(s)://url-to-gitlab
  #     force: true
  #     mirror:
  #       enabled: true

  ## Backup to Github repository
  # github:
  #   - token: some-token
  #     token_file: token.txt
  #     organization: myorg
  #     force: true
  #     visibility:
  #       repositories: private
