volumes:
  mc-data: {}
  mc-backups: {}

services:
  mc-server:
    image: itzg/minecraft-server:java21
    container_name: ${MC_SERVER_CONTAINER_NAME:-minecraft-pixelmon-server}
    ports:
      - ${MC_SERVER_PORT:-25565}:25565
      - ${MC_SERVER_RCON_PORT:-25575}
    environment:
      EULA: "true"
      SNOOPER_ENABLED: 'false'
      MODPACK_PLATFORM: MODRINTH
      MEMORY: ${MC_SERVER_MEMORY:-4}G
      MODRINTH_MODPACK: https://modrinth.com/modpack/the-pixelmon-modpack/version/${MC_SERVER_PIXELMON_VERSION:-9.2.10}
      PVP: ${MC_SERV_PVP:-true}
      ONLINE_MODE: ${MC_SERV_ONLINE_MODE:-true}
      WHITELIST_ENABLED: ${MC_SERVER_WHITELIST_ENABLE:-false}
      OVERRIDE_WHITELIST: true
      WHITELIST: ${MC_SERVER_WHITELISTED_PLAYERS}
      OPS: ${MC_SERVER_OPERATORS}
      MOTD: ${MC_SERV_MOTD:-Welcome to Pixelmon!}
      ALLOW_FLIGHT: 'true'
      GUI: 'FALSE'
      MAX_TICK_TIME: '-1'
      ENABLE_ROLLING_LOGS: 'true'
      TZ: ${TZ:-Etc/UTC}
      tty: ${MC_SERV_TTY:-'true'}
      stdin_open: 'true'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MC_SERVER_DATA_DIR:-mc-data}:/data
      - ${MC_SERVER_BACKUP_DIR:-mc-backups}:/data/simplebackups
    healthcheck:
        test: mc-health
        start_period: 1m
        interval: 5s
        retries: 20
