volumes:
  portall_data: {}

services:
  portall:
    image: need4swede/portall:latest
    container_name: portall
    ports:
      - ${PORTALL_WEBUI_PORT:-8080}:8080
    environment:
      - SECRET_KEY=${PORTALL_SECRET_KEY}
    volumes:
      - ${PORTALL_DATA_DIR:-portall_data}:/app/instance

