---
services:

    satisfactory-server:
        container_name: 'satisfactory-server'
        restart: unless-stopped
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - ${SERVER_PORT:-7777}:7777/udp
            - ${BEACON_PORT:-15000}:15000/udp
            - ${QUERY_PORT:-15777}:15777/udp
        volumes:
            - ${CONFIG_DIR:-./satisfactory/config}:/config
        environment:
            MAXPLAYERS: ${MAX_PLAYERS:-4}
            PGID: ${PGID:-1000}
            PUID: ${PUID:-1000}
            ROOTLESS: ${RUN_ROOTLESS:-false}
            STEAMBETA: ${STEAM_BETA:-false}
            AUTOPAUSE: ${AUTOPAUSE_WHEN_IDLE:-true}
            AUTOSAVEINTERNAL: ${AUTOPAUSE_INTERVAL:-300}
            AUTOSAVENUM: ${AUTOSAVE_COPIES:-5}
            AUTOSAVEONDISCONNECT: ${AUTOSAVE_ON_DISCONNECT:-true}
            CRASHREPORT: ${CRASH_REPORTING:-true}
            DEBUG: ${DEBUG:-false}
            DISABLESEASONALEVENTS: ${DISABLE_SEASONAL_EVENTS:-false}
            MAXOBJECTS: ${MAX_OBJECTS:-2162688}
            MAXTICKRATE: ${MAX_TICK_RATE:-30}
            NETWORKQUALITY: ${NETWORK_QUALITY:-3}
            SKIPUPDATE: ${SKIP_UPDATE:-false}
            TIMEOUT: ${TIMEOUT:-30}
        deploy:
          resources:
            limits:
              memory: ${RAM_LIMIT:-8G}
            reservations:
              memory: ${RAM_RESERVATION:-6G}
        labels:
          - "com.centurylinklabs.watchtower.enable=true"

    watchtower:
      image: containrrr/watchtower
      container_name: satisfactory-watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped
      environment:
        ## Remove old images after updating
        WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-"true"}
        ## Check for updates once every 24h
        WATCHTOWER_POLL_INTERVAL: ${WATCHTOWER_POLL_INTERVAL:-86400}
      ## Only monitor containers with a specific label
      command: --label-enable
