---
networks:
  openwebui_net: {}

volumes:
  ollama: {}
  open-webui: {}

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${OPENWEBUI_CONTAINER_VER:-ollama}
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "${OPENWEBUI_PORT:-3000}:8080"
    volumes:
      - ${OPENWEBUI_OLLAMA_DIR:-ollama}:/root/.ollama
      - ${OPENWEBUI_DATA_DIR:-open-webui}:/app/backend/data
    ## to use GPUs (requires NVIDIA runtime installed)
    # runtime: nvidia
    networks:
      - openwebui_net

  ## Watchtower container to keep webUI up to date
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    ## Ensure watchtower only runs once
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --run-once open-webui
    networks:
      - openwebui_net
