version: "3.7"

volumes:
  postgres_data:
  pgadmin_data:

# networks:
  # pg_net:

services:

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG:-bullseye}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ${POSTGRES_DATA_DIR:-postgres_data}:/var/lib/postgresql/data
      # Mount directory with init scripts for docker, i.e. install UUID extension
      - ./pg_entrypoint:/docker-entrypoint-initdb.d/
    # networks:
    #   - pg_net

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_IMAGE_TAG:-latest}
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-80}
    ports:
      - ${PGADMIN_PORT:-15432}:80
    volumes:
      - ${PGADMIN_DATA_DIR:-pgadmin_data}:/var/lib/pgadmin
    depends_on:
      - postgres
