---
name: renovatbot

volumes:
  cache: {}

services:
  renovate:
    image: renovate/renovate:${RENOVATE_IMG_TAG:-latest}
    container_name: renovate
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${RENOVATE_LOG_LEVEL:-info}
      LOG_FORMAT: ${RENOVATE_LOG_FORMAT:-json}
      RENOVATE_PLATFORM: ${RENOVATE_PLATFORM:-github}
      RENOVATE_AUTODISCOVER: ${RENOVATE_AUTODISCOVER:-false}
      RENOVATE_AUTODISCOVER_NAMESPACES: ${RENOVATE_AUTODISCOVER_NAMESPACES:-}
      RENOVATE_ENDPOINT: ${RENOVATE_ENDPOINT:-}
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES:-}
      RENOVATE_ONBOARDING: ${RENOVATE_ONBOARDING:-false}
      RENOVATE_REQUIRE_CONFIG: ${RENOVATE_REQUIRE_CONFIG:-optional}
      RENOVATE_DEPENDENCY_DASHBOARD: ${RENOVATE_DEPENDENCY_DASHBOARD:-true}
      RENOVATE_DRY_RUN: ${RENOVATE_DRY_RUN:-false}
      RENOVATE_BASE_DIR: /tmp/renovate
      RENOVATE_CONFIG_FILE: /usr/src/app/config.js
      RENOVATE_GITHUB_COM_TOKEN: ${RENOVATE_GITHUB_COM_TOKEN}
      RENOVATE_TOKEN: ${RENOVATE_TOKEN}
    volumes:
      - ${RENOVATE_CONFIG_FILE_PATH:-./config/config.js}:/usr/src/app/config.js:ro
      - ${RENOVATE_CACHE_DIR:-cache}:/tmp/renovate
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: ${RENOVATE_LOG_MAX_SIZE:-10m}
        max-file: ${RENOVATE_LOG_MAX_FILE:-3}
        compress: ${RENOVATE_LOG_COMPRESS:-true}
