---
name: crow-ci

volumes:
  server-data:
  agent-config:

services:
  server:
    image: codefloe.com/crowci/crow-server:v${CROW_IMG_TAG:-5.13}
    container_name: crow-server
    ports:
      - ${CROW_SERVER_HTTP_PORT:-8000}:8000
      - ${CROW_SERVER_GRPC_PORT:-9000}:9000
    volumes:
      - ${CROW_SERVER_DATA_DIR:-server-data}:/var/lib/crow
    environment:
      CROW_OPEN: ${CROW_SERVER_OPEN_MODE:-true}
      CROW_HOST: ${CROW_SERVER_HOST:-http://localhost:8000}
      CROW_AGENT_SECRET: ${CROW_AGENT_SECRET}
      CROW_FORGEJO: ${CROW_SERVER_ENABLE_FORGE_INTEGRATION:-false}
      CROW_FORGEJO_URL: ${CROW_FORGEJO_URL:-"https://codeberg.org"}
      CROW_FORGEJO_CLIENT: ${CROW_FORGEJO_CLIENT}
      CROW_FORGEJO_SECRET: ${CROW_FORGEJO_SECRET}
      CROW_MAX_WORKFLOWS: ${CROW_AGENT_MAX_WORKFLOWS:-2}
    logging:
      driver: json-file
      options:
        max-size: "${CROW_SERVER_LOG_MAX_SIZE:-10m}"
        max-file: "${CROW_SERVER_LOG_MAX_FILE:-5}"

  agent:
    image: codefloe.com/crowci/crow-agent:${CROW_IMG_TAG:-v5.13}
    container_name: crow-agent
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CROW_AGENT_CONFIG_DIR:-agent-config}:/etc/crow
    environment:
      CROW_SERVER: "server:9000"
      CROW_AGENT_SECRET: ${CROW_AGENT_SECRET}
    logging:
      driver: json-file
      options:
        max-size: "${CROW_AGENT_LOG_MAX_SIZE:-10m}"
        max-file: "${CROW_AGENT_LOG_MAX_FILE:-5}"
    deploy:
      resources:
        limits:
          cpus: "${CROW_AGENT_CPUS:-2}"
          memory: ${CROW_AGENT_MEMORY:-2G}
