networks:
  internal:
    driver: bridge

services:
  mc-server:
    image: itzg/minecraft-server:java21-alpine
    container_name: ${MC_SERV_CONTAINER_NAME:-mc-server_auto-forge}
    restart: unless-stopped
    hostname: minecraft-curseforge
    networks:
      - internal
    ports: 
      - ${MC_SERV_PORT:-25565}:25565
      - ${MC_SERV_RCON_PORT:-25575}:25575
    dns:
      # - 192.168.1.2
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    # dns_search: bit13.local

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: ${MC_SERV_MEMORY_MAX:-8g}
        reservations:
          memory: ${MC_SERV_MEMORY_MIN:-4g}
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: ${MC_SERVER_CURSE_FORGE_API_KEY}
      CF_SLUG: ${MC_SERV_CF_SLUG:-all-the-mods-10}
      VERSION: ${MC_SERVER_VERSION:-1.21.1}
      CF_FORCE_SYNCHRONIZE: true
      # CF_EXCLUDE_MODS: 986380, 520110, 394468, 447673, 927064
      # CF_FORCE_INCLUDE_MODS: ''
      CF_FORCE_REINSTALL_MODLOADER: true
      FETCH_TLS_HANDSHAKE_TIMEOUT: PT20S

      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_KNOCK_INTERFACE: ${MC_SERVER_AUTOPAUSE_KNOCK_INTERFACE:-'eth0'}

      # SEED: '8483537205'
      VIEW_DISTANCE: 10

      # ICON: "https://i.imgur.com/RV1PBPD.png"
      # OVERRIDE_ICON: 'TRUE'

      # OPS_FILE: './ops.json'
      WHITELIST_FILE: /extras/whitelist.json
      ENFORCE_WHITELIST: ${MC_SERV_WHITELIST_ENABLE:-'true'}
      OVERRIDE_WHITELIST: 'true'

      REMOVE_OLD_MODS: 'false'

      # LEVEL: taco_atm10-2

      MEMORY: 24G
      
      ENABLE_RCON: 'true'
      RCON_PASSWORD: ${MC_SERV_RCON_PASSWORD}
      BROADCAST_RCON_TO_OPS: 'true'

      ALLOW_NETHER: 'true'
      ANNOUNCE_PLAYER_ACHIEVEMENTS: 'true'
      STOP_SERVER_ANNOUNCE_DELAY: 60
      STOP_DURATION: 60
      
      MOTD: ${MC_SERV_MOTD:-Welcome to the Curse Forge Minecraft server!}
      MAX_PLAYERS: ${MC_SERV_MAX_PLAYERS:-20}
      SNOOPER_ENABLED: 'false'
      HARDCORE: 'false'
      DIFFICULTY: ${MC_SERV_DIFFICULTY:-normal}
      GENERATE_STRUCTURES: 'true'
      MAX_BUILD_HEIGHT: 256
      SPAWN_ANIMALS: 'true'
      SPAWN_NPCS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_PROTECTION: 0

      MODE: ${MC_SERV_GAME_MODE:-survival}
      PVP: ${MC_SERV_PVP:-false}

      LEVEL_TYPE: amplified
      ALLOW_FLIGHT: 'true'
      ENABLE_ROLLING_LOGS: 'true'
      MAX_TICK_TIME: "-1"
      GUI: 'FALSE'
      # UID: 1000
      # GID: 1000
      TZ: ${TZ:-Etc/UTC}
      EULA: 'true'
      tty: ${MC_SERV_TTY:-'true'}
      stdin_open: 'true'

    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ${MC_SERV_DATA_DIR:-./data/minecraft-server}:/data
    - ${MC_SERVER_MODS_FILE:-./mods_files/default.txt}:/extras/mods.txt
    - ${MC_SERVER_WHITELIST_FILE:-./whitelist.json}:/extras/whitelist.json
    - ${MC_SERVER_MODS_DIR:-./container_volumes/mods}:/mods
    - ${MC_SERVER_MODPACKS_DIR:-./container_volumes/modpacks}:/modpacks
    - ${MC_SERVER_DOWNLOADS_DIR:-./container_volumes/downloads}:/downloads
    - ${MC_SERVER_BACKUPS_DIR:-./container_volumes/backups}:/data/simplebackups

    healthcheck:
        test: mc-health
        start_period: 1m
        interval: 5s
        retries: 20