---
volumes:
  obsidian_vaults: {}
  obsidian_config: {}

services:
  obsidian:
    image: 'ghcr.io/sytone/obsidian-remote:latest'
    container_name: obsidian-remote
    restart: unless-stopped
    ports:
      - ${OBSIDIAN_HTTP_PORT:-8080}:8080
      - ${OBSIDIAN_HTTPS_PORT:-8443}:8443
    volumes:
      - ${OBSIDIAN_VAULTS_DIR:-obsidian_vaults}:/vaults
      - ${OBSIDIAN_CONFIG_DIR:-obsidian_config}:/config
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PUID:-1000}
      TZ: ${TZ:-Etc/UTC}
      DOCKER_MODS: linuxserver/mods:universal-git
      CUSTOM_PORT: 8080
      CUSTOM_HTTPS_PORT: 8443
      KEYBOARD: ${OBSIDIAN_KEYBOARD_LAYOUT:-en-us-qwerty}
      # CUSTOM_USER: ${OBSIDIAN_HTTP_USER:-obsidian}
      # PASSWORD: ${OBSIDIAN_HTTP_PASSWORD:-Obsidian!}
      TITLE: ${OBSIDIAN_HTTP_PAGE_TITLE:-Obsidian.md}
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1

