---
name: crow-ci-agent

services:
  agent:
    image: codefloe.com/crowci/crow-agent:${CROW_IMG_TAG:-v5.13}
    container_name: crow-agent
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CROW_AGENT_CONFIG_DIR:-agent-config}:/etc/crow
    environment:
      CROW_SERVER: ${CROW_AGENT_SERVER_URL}
      CROW_AGENT_SECRET: ${CROW_AGENT_SECRET}
      CROW_MAX_WORKFLOWS: ${CROW_AGENT_MAX_WORKFLOWS:-2}
