networks:
  mysql_workbench-net:
    name: mysql_workbench-net
    external: true

services:
  ## Web UI for database
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Etc/UTC}
      CUSTOM_PORT: ${MYSQL_WORKBENCH_CUSTOM_CONTAINER_HTTP_PORT:-3000}
      CUSTOM_HTTPS_PORT: ${MYSQL_WORKBENCH_CUSTOM_CONTAINER_HTTPS_PORT:-3001}
      ## WebUI page title
      TITLE: ${MYSQL_WORKBENCH_PAGE_TITLE:-"KasmVNC Client"}
      ## Uncomment to disable window borders, useful for running as PWA
      # NO_DECOR: 1
      ## Uncomment to disable automatic fullscreen apps when using openbox
      # NO_FULL: 1
      ## WebUI credentials
      CUSTOM_USER: ${MYSQL_WORKBENCH_USER:-abc}
      PASSWORD: ${MYSQL_WORKBENCH_PASSWORD:-abc}

    volumes:
      - ${MYSQL_WORKBENCH_CONF_DIR:-./data/config}:/config
    ports:
      - ${MYSQL_WORKBENCH_HTTP_PORT:-3000}:${MYSQL_WORKBENCH_CUSTOM_CONTAINER_HTTP_PORT:-3000}
      - ${MYSQL_WORKBENCH_HTTPS_PORT:-3001}:${MYSQL_WORKBENCH_CUSTOM_CONTAINER_HTTPS_PORT:-3001}
