---
services:

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: npm_proxy_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      ## Remove old images after updating
      WATCHTOWER_CLEANUP: ${WATCHTOWER_CLEANUP:-"true"}
      ## Check for updates once every 24h
      WATCHTOWER_POLL_INTERVAL: ${WATCHTOWWER_POLL_INTERVAL:-86400}
    command: --label-enable
