---
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      stop_grace_period: 30s
      ports:
        - ${PALWORLD_GAME_PORT:-8211}:8211/udp
        - ${PALWORLD_QUERY_PORT:-27015}:27015/udp
        - ${PALWORLD_RCON_PORT:-25575}:25575/tcp
        # - ${PALWORLD_REST_API_PORT:-8212}:8212/tcp  # Port for REST API if REST_API_ENABLED: true
      environment:
         ###########
         # General #
         ###########
         PUID: ${PUID:-1000}
         PGID: ${PGID:-1000}
         PORT: 8211
         PLAYERS: ${PALWORLD_MAX_PLAYERS:-16}
         SERVER_PASSWORD: ${PALWORLD_SERVER_PASSWORD:-"worldPals!"}
         MULTITHREADING: ${PALWORLD_MULTIHREADING:-true}
         REST_API_ENABLED: ${PALWORLD_REST_API_ENABLED:-false}
         RCON_ENABLED: ${PALWORLD_RCON_ENABLED:-true}
         RCON_PORT: 25575
         TZ: ${PALWORLD_TZ:-"UTC"}
         ADMIN_PASSWORD: ${PALWORLD_ADMIN_PASSWORD:-adminPasswordHere}
         
         ## Enable this if you want your server to show up in the community servers tab.
         #  USE A SERVER_PASSWORD IF TRUE!
         COMMUNITY: ${PALWORLD_ENABLE_COMMUNITY_LISTING:-false}
         SERVER_NAME: ${PALWORLD_SERVER_NAME:-"Docker Palworld"}
         SERVER_DESCRIPTION: ${PALWORLD_SERVER_DESCRIPTION:-"Dockerized Palworld server"}
          ## Defaults to "Steam" if not set, set this to "Xbox" if you want to host a server for Xbox players.
          #  CROSSPLAY BETWEEN XBOX-STEAM IS NOT YET SUPPORTED
         ALLOW_CONNECT_PLATFORM: ${PALWORLD_CONNECT_PLATFORM:-"Steam"}
         ## Manually set public IP if connection isn't working
         PUBLIC_IP: ${PALWORLD_PUBLIC_IP:-""}
         ## If you set a different port binding, set it here too
         PUBLIC_PORT: ${PALWORLD_GAME_PORT:-8211}

         ###########
         # Backups #
         ###########
         BACKUP_ENABLED: ${PALWORLD_ENABLE_BACKUPS:-false}
         ## Set cron schedule for backups
         BACKUP_CRON_EXPRESSION: ${PALWORLD_BACKUP_CRON:-*/30 * * * *}
         ## Set backup autodelete schedule
         DELETE_OLD_BACKUPS: ${PALWORLD_DELETE_OLD_BACKUPS:-true}
         OLD_BACKUP_DAYS: ${PALWORLD_DELETE_BACKUPS_AFTER_DAYS:-30}

         ###########
         # Updates #
         ###########
         UPDATE_ON_BOOT: ${PALWORLD_UPDATE_ON_BOOT:-true}
         AUTO_UPDATE_ENABLED: ${PALWORLD_ENABLE_AUTO_UPDATES:-true}
         AUTO_UPDATE_SCHEDULE: ${PALWORLD_AUTO_UPDATE_SCHEDULE:-0 */1 * * *}
         AUTO_UPDATE_WARN_MINUTES: ${PALWORLD_AUTO_UPDATE_WARN_MINUTES:-30}

         ###########
         # Reboots #
         ###########
         AUTO_REBOOT_ENABLED: ${PALWORLD_ENABLE_AUTO_REBOOTS:-true}
         AUTO_REBOOT_CRON_EXPRESSION: ${PALWORLD_AUTO_REBOOT_CRON:-30 3 * * *}
         AUTO_REBOOT_WARN_MINUTES: ${PALWORLD_AUTO_REBOOT_WARN_MINUTES:-30}
         AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE: ${PALWORLD_AUTO_REBOOT_EVEN_IF_PLAYERS_ONLINE:-false}
         
         ENABLE_PLAYER_LOGGING: ${PALWORLD_ANNOUNCE_PLAYERS:-false}
         PLAYER_LOGGING_POLL_PERIOD: ${PALWORLD_PLAYER_LOGGING_POLL_PERIOD:-5}

         ###################
         # Server Settings #
         ###################
         # DIFFICULTY: ${PALWORLD_SERVER_DIFFICULTY:-""} # Doesn't do anything
         DAYTIME_SPEEDRATE: ${PALWORLD_SERVER_DAYTIME_SPEEDRATE:-1.0}
         NIGHTTIME_SPEEDRATE: ${PALWORLD_SERVER_NIGHTTIME_SPEEDRATE:-1.0}
         EXP_RATE: ${PALWORLD_SERVER_EXP_RATE:-1.0}
         PAL_CAPTURE_RATE: ${PALWORLD_SERVER_PAL_CAPTURE_RATE:-1.0}
         PAL_SPAWN_NUM_RATE: ${PALWORLD_SERVER_PAL_SPAWN_NUM_RATE:-1.0}
         PAL_DAMAGE_RATE_ATTACK: ${PALWORLD_SERVER_PAL_DAMAGE_RATE_ATTACK:-1.0}
         PAL_DAMAGE_RATE_DEFENSE: ${PALWORLD_SERVER_PAL_DAMAGE_RATE_DEFENSE:-1.0}
         PLAYER_DAMAGE_RATE_ATTACK: ${PALWORLD_SERVER_PLAYER_DAMAGE_RATE_ATTACK:-1.0}
         PLAYER_DAMAGE_RATE_DEFENSE: ${PALWORLD_SERVER_PLAYER_DAMAGE_RATE_DEFENSE:-1.0}
         PLAYER_STOMACH_DECREASE_RATE: ${PALWORLD_SERVER_PLAYER_STOMACH_DECREASE_RATE:-1.0}
         PLAYER_STAMINA_DECREASE_RATE: ${PALWORLD_SERVER_PLAYER_STAMINA_DECREASE_RATE:-1.0}
         PLAYER_AUTO_HP_REGEN_RATE: ${PALWORLD_SERVER_PLAYER_AUTO_HP_REGEN_RATE:-1.0}
         PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: ${PALWORLD_SERVER_PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP:-1.0}
         PAL_STOMACH_DECREASE_RATE: ${PALWORLD_SERVER_PAL_STOMACH_DECREASE_RATE:-1.0}
         PAL_STAMINA_DECREASE_RATE: ${PALWORLD_SERVER_PAL_STAMINA_DECREATE_RATE:-1.0}
         PAL_AUTO_HP_REGEN_RATE: ${PALWORLD_SERVER_PAL_AUTO_HP_REGEN_RATE:-1.0}
         PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: ${PALWORLD_SERVER_PAL_AUTO_HP_REGEN_RATE_IN_SLEEP:-1.0}
         BUILD_OBJECT_DAMAGE_RATE: ${PALWORLD_SERVER_BUILD_OBJECT_DAMAGE_RATE:-1.0}
         BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: ${PALWORLD_SERVER_BUILD_OBJECT_DETERIORATION_DAMAGE_RATE:-1.0}
         COLLECTION_DROP_RATE: ${PALWORLD_SERVER_COLLECTION_DROP_RATE:-1.0}
         COLLECTION_OBJECT_HP_RATE: ${PALWORLD_SERVER_COLLECTION_OBJECT_HP_RATE:-1.0}
         COLLECTION_OBJECT_RESPAWN_SPEED_RATE: ${PALWORLD_SERVER_COLLECTION_OBJECT_RESPAWN_SPEED_RATE:-1.0}
         ENEMY_DROP_ITEM_RATE: ${PALWORLD_SERVER_ENEMY_DROP_ITEM_RATE:-1.0}
         ## Options: None, Item, ItemAndEquipment, All
         DEATH_PENALTY: ${PALWORLD_SERVER_DEATH_PENALTY:-Item}
         ENABLE_PLAYER_TO_PLAYER_DAMAGE: ${PALWORLD_SERVER_PLAYER_TO_PLAYER_DAMAGE:-false}
         ENABLE_FRIENDLY_FIRE: ${PALWORLD_SERVER_ENABLE_FRIENDLY_FIRE:-false}
         ENABLE_INVADER_ENEMY: ${PALWORLD_SERVER_ENABLE_INVASIONS:-true}
         ENABLE_AIM_ASSIST_PAD: ${PALWORLD_SERVER_ENABLE_CONTROLLER_AIM_ASSIST:-true}
         ENABLE_AIM_ASSIST_KEYBOARD: ${PALWORLD_SERVER_ENABLE_KEYBOARD_AIM_ASSIST:-false}
         ## Maximum number of drops in the world
         DROP_ITEM_MAX_NUM: ${PALWORLD_SERVER_DROP_ITEM_MAX_NUM:-3000}
         ## Maximum number of unko (?) drops in the world
         DROP_ITEM_MAX_NUM_UNKO: ${PALWORLD_SERVER_DROP_ITEM_MAX_NUM_UNKO:-100}
         BASE_CAMP_MAX_NUM: ${PALWORLD_SERVER_BASE_CAMP_MAX_NUM:-128}
         BASE_CAMP_WORKER_MAX_NUM: ${PALWORLD_SERVER_BASE_CAMP_WORKER_MAX_NUM:-15}
         ## Time it takes for items to despawn, in hours
         DROP_ITEM_ALIVE_MAX_HOURS: ${PALWORLD_SERVER_DROP_ITEM_ALIVE_MAX_HOURS:-1}
         AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: ${PALWORLD_SERVER_AUTO_RESET_GUILD_NO_ONLINE_PLAYERS:-false}
         ## Time, in hours, to reset guild when no guild player has been online
         AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: ${PALWORLD_SERVER_AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS:-""}
         GUILD_PLAYER_MAX_NUM: ${PALWORLD_SERVER_GUILD_PLAYER_MAX_NUM:-20}
         BASE_CAMP_MAX_NUM_IN_GUILD: ${PALWORLD_SERVER_BASE_CAMP_MAX_NUM_IN_GUILD:-4}
         ## Time in hours to incubate massive eggs
         PAL_EGG_DEFAULT_HATCHING_TIME: ${PALWORLD_SERVER_EGG_HATCHING_TIME:-3.0}
         WORK_SPEED_RATE: ${PALWORLD_SERVER_WORK_SPEED_RATE:-1.0}
         ## Time in seconds between autosaves
         AUTO_SAVE_SPAN: ${PALWORLD_SERVER_AUTO_SAVE_SPAN:-30}
         IS_MULTIPLAY: ${PALWORLD_SERVER_IS_MULTIPLAY:-true}
         IS_PVP: ${PALWORLD_SERVER_ENABLE_PVP:-false}
         CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: ${PALWORLD_SERVER_ENABLE_GUILD_PENALTY_DROP_PICKUP:-true}
         ENABLE_NON_LOGIN_PENALTY: ${PALWORLD_SERVER_ENABLE_NON_LOGIN_PENALTY:-false}
         IS_START_LOCATION_SELECT_BY_MAP: ${PALWORLD_SERVER_ALLOW_SELECT_START_LOCATION:-true}
         EXIST_PLAYER_AFTER_LOGOUT: ${PALWORLD_SERVER_EXIST_PLAYER_AFTER_LOGOUT:-false}
         ENABLE_DEFENSE_OTHER_GUILD_PLAYER: ${PALWORLD_SERVER_ENABLE_DEFENSE_OTHER_GUILD_PLAYER:-false}
         INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX: ${PALWORLD_SERVER_INVISIBLE_OTHER_GUILD_BASE_CAMP_AREA_FX:-false}
         ## Maximum number of players in a guild
         COOP_PLAYER_MAX_NUM: ${PALWORLD_SERVER_COOP_PLAYER_MAX_NUM:-4}
         USEAUTH: ${PALWORLD_SERVER_USEAUTH:-true}
         BAN_LIST_URL: ${PALWORLD_SERVER_BAN_LIST_URL:-"https://api.palworldgame.com/api/banlist.txt"}
         SHOW_PLAYER_LIST: ${PALWORLD_SERVER_SHOW_PLAYER_LIST:-true}
         ## Time in minutes between supply drops
         SUPPLY_DROP_SPAN: ${PALWORLD_SERVER_SUPPLY_DROP_SPAN:-180}

      volumes:
         - ${PALWORLD_DATA_DIR:-./palworld/data}:/palworld/
         - ${PALWORLD_BACKUP_DIR:-./palworld/backups}:/palworld/backups
