---
name: davis-sqlite

volumes:
  davis_data: {}
  davis_webdav: {}

services:
  davis:
    image: ghcr.io/tchapi/davis-standalone:latest
    container_name: davis
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_DRIVER: sqlite
      DATABASE_URL: sqlite:////data/davis-database.db

      ## Admin credentials
      ADMIN_LOGIN: ${ADMIN_LOGIN:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}

      ## Authentication
      AUTH_REALM: ${AUTH_REALM:-Davis DAV Server}
      AUTH_METHOD: ${AUTH_METHOD:-Basic}

      ## Features
      CALDAV_ENABLED: ${CALDAV_ENABLED:-true}
      CARDDAV_ENABLED: ${CARDDAV_ENABLED:-true}
      WEBDAV_ENABLED: ${WEBDAV_ENABLED:-false}

      WEBDAV_TMP_DIR: /tmp
      WEBDAV_PUBLIC_DIR: /webdav/public
      WEBDAV_HOMES_DIR: /webdav/homes

      PUBLIC_CALENDARS_ENABLED: ${PUBLIC_CALENDARS_ENABLED:-true}

      INVITE_FROM_ADDRESS: ${INVITE_FROM_ADDRESS:-davis@example.com}

      APP_TIMEZONE: ${APP_TIMEZONE:-Etc/UTC}

      ## Optional extras
      BIRTHDAY_REMINDER_OFFSET: ${BIRTHDAY_REMINDER_OFFSET:-PT9H}
      SYMFONY_TRUSTED_PROXIES: ${SYMFONY_TRUSTED_PROXIES:-0.0.0.0/0}
    volumes:
      - ${DAVIS_DATA_DIR:-davis_data}:/data
      - ${DAVIS_WEBDAV_DIR:-davis_webdav}:/webdav
    ports:
      - "${DAVIS_PORT:-9000}:9000"
