http:
  routers:
    gitlab-router:
      rule: "Host(`gitlab.example.com`)"
      entryPoints:
        - websecure
      service: gitlab-service
      tls:
        certResolver: letsencrypt

  services:
    gitlab-service:
      loadBalancer:
        servers:
          - url: "http://gitlab-server:80"
