---
name: feedbin

volumes:
  pgdata: {}
  feedbin-data: {}

services:
  feedbin-web:
    image: angristan/feedbin:latest
    restart: unless-stopped
    depends_on:
      - postgresql
      - redis
      - memcached
      - minio
      - elasticsearch
    environment:
      FEEDBIN_HOST: ${FEEDBIN_HOST:-feedbin.example.com}
      FEEDBIN_PORT: "3000"
      RAILS_ENV: production
      SECRET_KEY_BASE: ${FEEDBIN_SECRET_KEY_BASE:-your_random_secret_key_base}
      POSTGRES_HOST: ${FEEDBIN_DB_HOST:-postgresql}
      POSTGRES_USER: ${DB_USER:-feedbin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-feedbinpassword}
      POSTGRES_DB: ${FEEDBIN_DB_DATABASE:-feedbindb}
      REDIS_URL: ${FEEDBIN_REDIS_URL:-redis://redis:6379/0}
      MEMCACHED_SERVERS: ${FEEDBIN_MEMCACHED_URL:-memcached:11211}
      MINIO_ENDPOINT: ${FEEDBIN_MINIO_ENDPOINT:-minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioaccesskey}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniosecretkey}
      MINIO_BUCKET: ${MINIO_BUCKET:-feedbin}
      ELASTICSEARCH_URL: ${FEEDBIN_ELASTICSEARCH_URL:-http://elasticsearch:9200}
      EXTRACT_HOST: feedbin-extract
      EXTRACT_PORT: "5000"
      CAMO_HOST: feedbin-camo
      CAMO_PORT: "4000"
      CAMO_KEY: ${FEEDBIN_CAMO_KEY:-your_camo_key}
      SMTP_ADDRESS: ${FEEDBIN_SMTP_ADDRESS}
      SMTP_PORT: ${FEEDBIN_SMTP_PORT:-"587"}
      SMTP_USER: ${FEEDBIN_SMTP_USER}
      SMTP_PASSWORD: ${FEEDBIN_SMTP_PASSWORD}
      SMTP_DOMAIN: ${FEEDBIN_SMTP_DOMAIN}
      SMTP_AUTHENTICATION: ${FEEDBIN_SMTP_AUTH_TYPE:-plain}
      SMTP_ENABLE_STARTTLS_AUTO: ${FEEDBIN_SMTP_STARTTLS_AUTO:-"true"}
    ports:
      - ${FEEDBIN_HTTP_PORT:-3000}:3000
    volumes:
      - ${FEEDBIN_DATA_DIR:-feedbin}-data:/feedbin/data
    command: ${FEEDBIN_CMD:-bundle exec puma -C config/puma.rb}

  feedbin-workers:
    image: angristan/feedbin:latest
    restart: unless-stopped
    depends_on:
      - redis
      - postgresql
      - memcached
      - minio
    environment:
      # Same as feedbin-web or define required subset here
      REDIS_URL: ${FEEDBIN_REDIS_URL:-redis://redis:6379/0}
      POSTGRES_HOST: ${FEEDBIN_DB_HOST:-postgresql}
      POSTGRES_USER: ${DB_USER:-feedbin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-feedbinpassword}
      POSTGRES_DB: ${FEEDBIN_DB_DATABASE:-feedbindb}
      MEMCACHED_SERVERS: ${FEEDBIN_MEMCACHED_URL:-memcached:11211}
      MINIO_ENDPOINT: ${FEEDBIN_MINIO_ENDPOINT:-minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioaccesskey}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniosecretkey}
    command: bundle exec sidekiq -C config/sidekiq.yml

  postgresql:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-feedbin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-feedbinpassword}
      POSTGRES_DB: ${FEEDBIN_DB_DATABASE:-feedbindb}

  redis:
    image: redis:6-alpine
    restart: unless-stopped

  memcached:
    image: memcached:alpine
    restart: unless-stopped

  minio:
    image: minio/minio
    restart: unless-stopped
    ports:
      - ${MINIO_PORT:-9000}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioaccesskey}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-miniosecretkey}
    command: server /data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    restart: unless-stopped
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
