---
name: gotify

volumes:
  caddy_data: {}
  caddy_config: {}

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - ${CADDY_HTTP_PORT:-80}:80
      - ${CADDY_HTTPS_PORT:-443}:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-}
      GOTIFY_PORT: ${GOTIFY_PORT:-8080}
    volumes:
      - ${CADDYFILE:-./Caddyfile}:/etc/caddy/Caddyfile
      - ${CADDY_DATA_DIR:-caddy_data}:/data
      - ${CADDY_CONFIG_DIR:-caddy_config}:/config
