---
name: homeassistant

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - ${MQTT_PORT:-1883}:1883
      - ${MQTT_HTTP_PORT:-9001}:9001
    volumes:
      - "${MQTT_CONFIG_DIR:-./config/mosquitto}:/mosquitto/config"
      - "${MQTT_DATA_DIR:-./data/mosquitto}:/mosquitto/data"
      - "${MQTT_LOGS_DIR:-./logs/mosquitto}:/mosquitto/log"
    environment:
      TZ: ${TZ:-America/New_York}
    user: "${PUID:-1883}:${PGID:-1883}"
