---
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: pangolin-crowdsec
    restart: unless-stopped
    command: -t
    environment:
      GID: "1000"
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      ENROLL_INSTANCE_NAME: "pangolin-crowdsec"
      PARSERS: crowdsecurity/whitelists
      ENROLL_TAGS: docker
    healthcheck:
      test: ["CMD", "cscli", "capi", "status"]
    labels:
      ## Disable traefik for crowdsec
      - "traefik.enable=false"
    volumes:
      ## crowdsec config
      - ./config/crowdsec:/etc/crowdsec
      ## crowdsec db
      - ./config/crowdsec:/var/lib/crowdsec/data
      ## log bind mounts into crowdsec
      ## traefik logs
      - ./config/logs/traefik:/var/log/traefik
    ports:
      ## metrics endpoint for prometheus
      - ${CROWDSEC_PROMETHEUS_METRICS_PORT:-6060}:6060

