---
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:${FLARESOLVERR_IMG_TAG:-latest}
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${FLARESOLVERR_LOG_LEVEL:-info}
    # ports:
    #   - ${FLARSOLVERR_PORT:-8191}:8191
