---
name: loki

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - ${GRAFANA_HTTP_PORT:-3000}:3000
    volumes:
      - ${GRAFANA_DATA_DIR:-grafana_data}:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_ANONYMOUS_LOGIN:-true}
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    depends_on:
      - loki
