---
volumes: 
  gitlab_runner_config: {}

services:

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GITLAB_RUNNER_CONFIG_DIR:-gitlab_runner_config}:/etc/gitlab-runner
