---
services:

  traefik:
    image: traefik:v${TRAEFIK_IMG_VER:-3.5.1}
    container_name: traefik
    restart: unless-stopped
    network_mode: host
    command:
      - "--configFile=/etc/traefik/traefik_config.yml"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    environment:
      TRAEFIK_ACME_EMAIL: ${TRAEFIK_ACME_EMAIL:-none@example.com}
      CLOUDFLARE_DNS_API_TOKEN: ${CF_API_TOKEN}
    volumes:
      - "${TRAEFIK_LETSENCRYPT_DIR:-./traefik/letsencrypt}:/letsencrypt"
      - ${TRAEFIK_CONFIG_FILE:-./config/traefik/traefik_config.yml}:/etc/traefik/traefik_config.yml:ro
      - ${TRAEFIK_DYNAMIC_CONFIG_FILE:-./config/traefik/dynamic_config.yml}:/etc/traefik/dynamic_config.yml:ro
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"

  gitlab-server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.routers.gitlab.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
