http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https

  ## Whitelist middleware for internal IPs
    #  Crowdsec feature
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "192.168.1.0/24"
          - "172.16.0.0/12"
    
    ## Basic security headers
    #  Crowdsec feature
    security-headers:
      headers:
        ## Custom response headers
        customResponseHeaders:
          ## Remove server header
          Server: "" 
          ## Remove powered by header
          X-Powered-By: "" 
          ## Set forwarded proto to https
          X-Forwarded-Proto: "https"  
        ## SSL proxy headers
        sslProxyHeaders: 
          ## Set forwarded proto to https
          X-Forwarded-Proto: "https" 
        ## Hosts proxy headers
        hostsProxyHeaders: 
          ## Set forwarded host
          - "X-Forwarded-Host" 
        ## Prevent MIME sniffing
        contentTypeNosniff: true 
        ## Set frame options
        customFrameOptionsValue: "SAMEORIGIN" 
        ## Set referrer policy
        referrerPolicy: "strict-origin-when-cross-origin" 
        ## Force STS header
        forceSTSHeader: true 
        ## Include subdomains
        stsIncludeSubdomains: true 
        ## STS seconds
        stsSeconds: 63072000 
        ## Preload STS
        stsPreload: true

    ## CrowdSec configuration with proper IP forwarding
    crowdsec:
      plugin:
        crowdsec:
          ## Enable CrowdSec plugin
          enabled: true
          ## Log level
          logLevel: INFO
          ## Update interval
          updateIntervalSeconds: 15
          ## Update max failure
          updateMaxFailure: 0
          ## Default decision seconds
          defaultDecisionSeconds: 15
          ## HTTP timeout
          httpTimeoutSeconds: 10
          ## CrowdSec mode
          crowdsecMode: live
          ## Enable AppSec
          crowdsecAppsecEnabled: true
          ## CrowdSec IP address which you noted down later
          crowdsecAppsecHost: crowdsec:7422
          ## Block on failure
          crowdsecAppsecFailureBlock: true
          ## Block on unreachable
          crowdsecAppsecUnreachableBlock: true
          crowdsecAppsecBodyLimit: 10485760
          ## CrowdSec API key which you noted down later
          crowdsecLapiKey: "<PUT_YOUR_BOUNCER_KEY_HERE_OR_IT_WILL_NOT_WORK>"
          ## CrowdSec  
          crowdsecLapiHost: crowdsec:8080
          ## CrowdSec API scheme
          crowdsecLapiScheme: http
          ## Forwarded headers trusted IPs
          forwardedHeadersTrustedIPs:
            ## All IP addresses are trusted for forwarded headers
            - "0.0.0.0/0"
          ## Client trusted IPs
          clientTrustedIPs:
            ## Internal LAN IP addresses
            - "10.0.0.0/8"
            ## Internal LAN IP addresses
            - "172.16.0.0/12"
            ## Internal LAN IP addresses
            - "192.168.0.0/16"
            ## Internal LAN IP addresses
            - "100.89.137.0/20"

  routers:
    main-app-router-redirect:
      rule: "Host(`proxy.<your.domain>`)"
      service: next-service
      entryPoints:
        - web
      middlewares:
        - redirect-to-https

    next-router:
      rule: "Host(`proxy.<your.domain>`) && !PathPrefix(`/api/v1`)"
      service: next-service
      entryPoints:
        - websecure
      middlewares:
        ## Add security headers middleware
        #  Crowdsec feature
        - security-headers
      tls:
        certResolver: letsencrypt
        domains:
          - main: "<your.domain>"
            sans:
              - "*.<your.domain>"

    api-router:
      rule: "Host(`proxy.<your.domain>`) && PathPrefix(`/api/v1`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        ## Add security headers middleware
        #  Crowdsec feature
        - security-headers
      tls:
        certResolver: letsencrypt

    ws-router:
      rule: "Host(`proxy.<your.domain>`)"
      service: api-service
      entryPoints:
        - websecure
      middlewares:
        ## Add security headers middleware
        #  Crowdsec feature
        - security-headers
      tls:
        certResolver: letsencrypt

  services:
    next-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:8000"

    api-service:
      loadBalancer:
        servers:
          - url: "http://pangolin:3000"
