api:
  insecure: true
  dashboard: true

providers:
  http:
    endpoint: "http://pangolin:3001/api/v1/traefik-config"
    pollInterval: "5s"
  file:
    filename: "/etc/traefik/dynamic_config.yml"

experimental:
  plugins:
    badger:
      moduleName: "github.com/fosrl/badger"
      ## Use latest version from:
      #  https://github.com/fosrl/badger/releases
      version: "v1.1.0"

log:
  level: "INFO"
  format: "common"

certificatesResolvers:
  letsencrypt:
    acme:
      ## Uncomment only 1 below, either
      #  httpChallenge OR dnsChallenge
      # httpChallenge:
      #   entryPoint: web
      dnsChallenge:
        ## https://doc.traefik.io/traefik/https/acme/#providers
        provider: "cloudflare"
      email: "<Your Cloudflare email>"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "30m"
    http:
      tls:
        certResolver: "letsencrypt"

serversTransport:
  insecureSkipVerify: true
