---
networks:
  media-net:
      driver: bridge

services:

  jackett:
    image: ${JACKETT_IMAGE:-linuxserver/jackett}
    container_name: ${JACKETT_NAME:-jackett}
    restart: ${JACKETT_RESTART:-unless-stopped}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${JACKETT_CONFIG_DIR:-./apps/jackett/config}:/config
      - ${JACKETT_PICONS_DIR:-./apps/jackett/picons}:/picons
      - ${JACKETT_DOWNLOADS:-./apps/jackett/downloads}:/downloads
    ports:
      - ${JACKETT_PORT:-9117}:9117
    networks:
      - media-net

  sonarr:
    image: ${SONARR_IMAGE:-linuxserver/sonarr}
    container_name: ${SONARR_NAME:-sonarr}
    restart: "${SONARR_RESTART:-unless-stopped}"
    links:
      - jackett:jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-American/New_York}
    volumes:
      - "${SONARR_CONF_DIR:-./apps/sonarr/config}:/config"
      - "${TV_DIR:-./apps/sonarr/tv}:/tv"
      # - "${SONARR_DOWNLOADS:-./apps/sonarr/downloads}:/downloads"
    ports:
      - ${SONARR_PORT:-8989}:8989
    networks:
      - media-net
    

  radarr:
    image: ${RADARR_IMAGE:-linuxserver/radarr}
    container_name: ${RADARR_CONTAINER_NAME:-radarr}
    restart: ${RADARR_RESTART:-unless-stopped}
    links:
      - jackett:jackett
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${RADARR_CONFIG_DIR:-./apps/radarr/config}:/config
      - ${BOOKS_DOWNLOAD_DIR:-./apps/radarr/downloads}:/downloads
      - ${MOVIES_DIR:-./apps/radarr/movies}:/movies
    ports:
      - ${RADARR_PORT:-7878}:7878
    networks:
      - media-net

  bazarr:
    image: ${BAZARR_IMAGE:-linuxserver/bazarr}
    container_name: ${BAZARR_NAME:-bazarr}
    restart: ${BAZARR_RESTART:-unless-stopped}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID-1000}
      - TZ=${TZ}
      - UMASK_SET=${BAZARR_UMASK:-022}
    volumes:
      - ${BAZARR_CONFIG_DIR:-./apps/bazarr/data}:/config
      - ${MOVIES_DIR:-./apps/bazarr/movies}:/movies
      - ${TV_DIR:-./apps/bazarr/tv}:/tv
    ports:
      - ${BAZARR_PORT:-6767}:6767
    # expose:
    #   - 6767
    networks:
      - media-net
