---
networks:
  rsshub_net: {}

volumes:
  rsshub_redis_data: {}

services:
  rsshub:
    image: diygod/rsshub:chromium-bundled
    container_name: rsshub
    restart: unless-stopped
    ports:
      - ${RSSHUB_WEBUI_PORT:-1200}:1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
    depends_on:
      - redis
    networks:
      - rsshub_net

  redis:
    image: redis:alpine
    container_name: rsshub-redis
    restart: unless-stopped
    volumes:
      - ${RSSHUB_REDIS_DATA_DIR:-rsshub_redis_data}:/data
    networks:
      - rsshub_net
