---
networks:
  semaphore_net: {}

volumes:
  semaphore_postgres: {}

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    ports:
      - ${SEMAPHORE_WEBUI_PORT:-3000}:3000
    environment:
      SEMAPHORE_DB_USER: ${SEMAPHORE_DB_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASSWORD:-semaphore}
      ## For postgres, change to: postgres
      SEMAPHORE_DB_HOST: postgres
      ## Change to 5432 for postgres
      SEMAPHORE_DB_PORT: ${SEMAPHORE_DB_PORT:-5432}
      ## For postgres, change to: postgres
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: ${SEMAPHORE_DB_DATABASE:-semaphore}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD:-changeme}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}
      SEMAPHORE_ADMIN: admin
      ## Generate with: head -c32 /dev/urandom | base64
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY}
      ## If you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_ACTIVATED: ${SEMAPHORE_ENABLE_LDAP:-'no'}
      SEMAPHORE_LDAP_HOST: ${SEMAPHORE_LDAP_HOST}
      SEMAPHORE_LDAP_PORT: ${SEMAPHORE_LDAP_PORT:-'636'}
      SEMAPHORE_LDAP_NEEDTLS: ${SEMAPHORE_LDAP_REQUIRE_TLS:-'yes'}
      SEMAPHORE_LDAP_DN_BIND: ${SEMAPHORE_LDAP_DN_BIND_STRING:-'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'}
      SEMAPHORE_LDAP_PASSWORD: ${SEMAPHORE_LDAP_PASSWORD}
      SEMAPHORE_LDAP_DN_SEARCH: ${SEMAPHORE_LDAP_DN_SEARCH_STRING:-'cn=users,cn=accounts'}
      SEMAPHORE_LDAP_SEARCH_FILTER: ${SEMAPHORE_LDAP_SEARCH_FILTER_STRING:-"(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"}
      TZ: ${TZ:-Etc/UTC}
    depends_on:
      - postgres

  postgres:
    image: postgres:${SEMAPHORE_POSTGRES_CONTAINER_VERSION:-14}
    container_name: semaphore_postgres
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ${SEMAPHORE_POSTGRES_DATA_DIR:-semaphore_postgres}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphore
      POSTGRES_DB: semaphore
