---
name: copyparty

volumes:
  fileshare: {}

services:
  copyparty:
    image: copyparty/ac:${COPYPARTY_IMG_TAG:-1.20.23}
    user: "${PUID:-1000}:${PGID:-1000}"
    ports:
      - ${COPYPARTY_HTTP_PORT:-3923}:3923
    volumes:
      - ${COPYPARTY_CONF_DIR:-./config}:/cfg:z
      - ${COPYPARTY_FILESHARE_ROOT_DIR:-fileshare}:/w
    environment:
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.${COPYPARTY_MINALLOC:-NOPE}
      PYTHON_UNBUFFERED: 1
    ## Allow thumbnailer to finish after shutdown signal
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q 127.0.0.1:3923/?reset=/._"]
      interval: 1m
      timeout: 2s
      retries: 5
      start_period: 15s
