---
version: "3"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-America/New_York}
    volumes:
      - ${FRESHRSS_CONFIG_DIR:-./data/config}:/config
    ports:
      - ${FRESHRSS_WEB_PORT:-80}:80
    restart: unless-stopped

