---
name: freshrss

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    restart: unless-stopped
    container_name: freshrss
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${FRESHRSS_CONFIG_DIR:-./data/config}:/config
      - ${FRESHRSS_EXTENSIONS_DIR:-./extensions}:/var/www/FreshRSS/extensions
    ports:
      - ${FRESHRSS_WEB_PORT:-80}:80

