# docker run -d -p 80:3000 --restart=always --env-file .env.huginn -v huginn-data:/var/lib/mysql huginn/huginn
version: "3.7"

volumes:
  huginn_data:

services:

  huginn:
    container_name: huginn
    image: huginn/huginn
    restart: unless-stopped
    ports:
      - ${HUGINN_WEB_PORT:-3000}:3000
    env_file: .env.huginn
    volumes:
      - ${HUGINN_DATA_DIR:-huginn_data}:/var/lib/mysql